### ISSUE TITLE
Migration to version 11.0

### ISSUE THREAD

**Issue by pedrobaeza** [OCA/queue#29]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-11.0

# Modules to migrate

- [x] queue_job (@lepistone and @guewen) #30 
- [x] queue_job_subscribe (@guewen) #31 
- [x] test_queue_job (@lepistone and @guewen) #30

**Comment by pedrobaeza** [comment]
Everything migrated, so I close.
