### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/queue#459]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [ ] base_export_async
- [ ] base_import_async
- [x] queue_job
- [x] queue_job_cron - By @baimont - #461
- [ ] queue_job_cron_jobrunner
- [ ] queue_job_subscribe
- [ ] test_base_import_async
- [x] test_queue_job

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by dzungtran89** [comment]
- base_import_async: WIP

**Comment by sonhd91** [comment]
`test_base_import_async`: WIP

**Comment by kikopeiro** [comment]
- base_export_async: https://github.com/OCA/queue/pull/553

**Comment by BT-anieto** [comment]
Missing **queue_job_batch**

**Comment by dtorreskaertech** [comment]
> * base_import_async: WIP

Incorrect CSS selector

![image](https://github.com/OCA/queue/assets/125234673/906823da-928a-4dfe-a0ec-ee6a1a21f7b2)
![image](https://github.com/OCA/queue/assets/125234673/07098095-fd41-49a1-b5cd-204bf5408a3c)

**Comment by kikopeiro** [comment]
CC @dtorreskaertech
