### ISSUE TITLE
Migration to version 18.0

### ISSUE THREAD

**Issue by AlexanderPashuk** [OCA/queue#688]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0

# Modules to migrate
- [ ] base_export_async
- [ ] base_import_async
- [ ] queue_job
- [ ] queue_job_cron
- [ ] queue_job_cron_jobrunner
- [ ] queue_job_subscribe
- [ ] test_base_import_async
- [ ] test_queue_job

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by AlexanderPashuk** [comment]
Hi @guewen,

Could you please create branch for 18.0 versions? I want to create PR for queue_job and queue_job_subscribe modules but can't do so until there will be such branch in original repository (because of official guide - https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-18.0#technical-method-to-migrate-a-module-from-170-to-180-branch)

If it is not a problem, I can create PR from my repository where we pushed migrated versions: https://github.com/AlexanderPashuk/queue/tree/18.0. We really need to have these modules migrated as soon as possible :)

Thank you!

**Comment by okuryan** [comment]
@pedrobaeza can you help with this? We can create PR once 18.0 branch is created.

**Comment by pedrobaeza** [comment]
Please follow news in https://github.com/OCA/maintainer-tools/issues/628

**Comment by AlexanderPashuk** [comment]
Closed as duplicate of https://github.com/OCA/queue/issues/691
